[workspace]
members = ["tests"]

[package]
name = "bincode-trait-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["derive"] }
quote = "1.0"
proc-macro2 = "1.0"
bincode = "2.0.1"
